In [1]:
from pythtb import Lattice
import numpy as np

In [2]:
lat_vecs = [[1, 0], [1/2, np.sqrt(3)/2]]
orb_vecs = [[1/3, 1/3], [2/3, 2/3]]

In [3]:
lat = Lattice(orb_vecs=orb_vecs, lat_vecs=lat_vecs, periodic_dirs=[0, 1])

In [4]:
print(lat)

----------------------------------------
       Lattice structure report         
----------------------------------------
r-space dimension           = 2
k-space dimension           = 2
periodic directions         = [0, 1]
number of orbitals          = 2

Lattice vectors (Cartesian):
  # 0 ===> [ 1.000,  0.000]
  # 1 ===> [ 0.500,  0.866]
Volume of unit cell (Cartesian) = 0.866 [A^d]

Reciprocal lattice vectors (Cartesian):
  # 0 ===> [ 6.283, -3.628]
  # 1 ===> [ 0.000,  7.255]
Volume of reciprocal unit cell = 45.586 [A^-d]

Orbital vectors (Cartesian):
  # 0 ===> [ 0.500,  0.289]
  # 1 ===> [ 1.000,  0.577]
Orbital vectors (fractional):
  # 0 ===> [ 0.333,  0.333]
  # 1 ===> [ 0.667,  0.667]
No symmetry operations registered.

----------------------------------------


In [5]:
lat.get_orb_vecs(cartesian=True)

array([[0.5       , 0.28867513],
       [1.        , 0.57735027]])

In [6]:
print(lat.get_recip_lat_vecs())
print(lat.recip_lat_vecs)

[[ 6.28318531 -3.62759873]
 [ 0.          7.25519746]]
[[ 6.28318531 -3.62759873]
 [ 0.          7.25519746]]


In [7]:
overlap_mat = lat.lat_vecs @ lat.recip_lat_vecs.T
print(overlap_mat/(2*np.pi))

[[ 1.00000000e+00  0.00000000e+00]
 [-4.79476621e-17  1.00000000e+00]]


In [8]:
print(lat.recip_volume, lat.cell_volume)

45.58575006211245 0.8660254037844386


In [9]:
from pythtb.lattice import Lattice, SymmetryOperation
import numpy as np

In [10]:
avec = [[1,0,0],[0,1,0],[0,0,1]]
orbs = [[0,0,0],[1/3,2/3,0]]
per  = [0,1]  # 2D periodic slab with a nonperiodic z

In [11]:
# C3z rotation in reduced coords around z (acts only on x,y block)
theta = 2*np.pi/3
R = np.array(
    [[np.cos(theta), -np.sin(theta), 0],
     [np.sin(theta),  np.cos(theta), 0],
     [0,              0,             1]], 
    float)

In [12]:
# In reduced lattice basis a proper C3 on a hex lattice is integer-like on the periodic subspace.
# For a generic basis, you’ll typically use the integer form (e.g., [[0,-1],[1,-1]]) in the periodic block.
lat = Lattice(avec, orbs, periodic_dirs=per)
lat.add_symmetry_operation(R, t=[0,0,0], label='C3z')

In [13]:
print(lat)

----------------------------------------
       Lattice structure report         
----------------------------------------
r-space dimension           = 3
k-space dimension           = 2
periodic directions         = [0, 1]
number of orbitals          = 2

Lattice vectors (Cartesian):
  # 0 ===> [ 1.000,  0.000,  0.000]
  # 1 ===> [ 0.000,  1.000,  0.000]
  # 2 ===> [ 0.000,  0.000,  1.000]
Volume of unit cell (Cartesian) = 1.000 [A^d]

Reciprocal lattice vectors (Cartesian):
  # 0 ===> [ 6.283,  0.000,  0.000]
  # 1 ===> [ 0.000,  6.283,  0.000]
Volume of reciprocal unit cell = 39.478 [A^-d]

Orbital vectors (Cartesian):
  # 0 ===> [ 0.000,  0.000,  0.000]
  # 1 ===> [ 0.333,  0.667,  0.000]
Orbital vectors (fractional):
  # 0 ===> [ 0.000,  0.000,  0.000]
  # 1 ===> [ 0.333,  0.667,  0.000]
Symmetry operations (reduced-coord representation):
  # 0 [C3z]  R=
[[-0.500, -0.866,  0.000],
 [ 0.866, -0.500,  0.000],
 [ 0.000,  0.000,  1.000]]
           t=[ 0.000,  0.000,  0.000]

--------

In [14]:
ok = lat.check_symmetry()
print(ok)

{'lattice_ok': False, 'orbitals_ok': False, 'bad_ops_lattice': [0], 'bad_ops_orbitals': [0]}


In [15]:
# # k-space helpers
# Gamma = np.array([0.0,0.0,0.0])
# Kstar = lat.star_of_k(np.array([1/3,1/3,0.0]))
# keepers = lat.little_group(Gamma)

In [16]:
# 2D periodic (x,y), z nonperiodic example
lat = Lattice(
    lat_vecs=np.array([[1,0,0],[0,1,0],[0,0,1]], float),
    orb_vecs=np.array([[0,0,0],[1/3,2/3,0]], float),
    periodic_dirs=[0,1]
)

# Proper reduced-basis C3 around a lattice site
lat.add_symmetry_operation(
    R=[[0,-1,0],[1,-1,0],[0,0,1]],
    t=[0,0,0],
    label="C3z"
)

print(lat.check_symmetry())
# Expect {'lattice_ok': True, 'orbitals_ok': True, ...}

{'lattice_ok': True, 'orbitals_ok': True, 'bad_ops_lattice': [], 'bad_ops_orbitals': []}


In [17]:
from pythtb.models import fu_kane_mele

model = fu_kane_mele(1, 1, 1, 1)

In [18]:
model.lattice.visualize_3d(n_cells=3)